# This is a basic workflow to help you get started with Actions

name: docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
        - run: yarn && yarn typedoc --out docs/ src/ && git add . && git commit -m "chore: update docs [skip ci]"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
  
